AllowCurtailment: 1
BoundarySectorData: ''
BoundarySectorInterconnections: tests/dummy_data/boundary_sector/BS_Flood_control.csv
BoundarySectorMaxSpillage: ''
BoundarySectorNTC: tests/dummy_data/boundary_sector/BS_AlertLevel.csv
CostCurtailment: ''
CostH2Slack: ''
CostHeatSlack: ''
CostLoadShedding: ''
CostNotServed: ''
CostOfSpillage: tests/dummy_data/boundary_sector/BS_Spillage_cost.csv
CostXNotServed: ''
CostXSpillage: ''
CplexAccuracy: 0.0006
CplexSetting: Default
DataTimeStep: 1.0
Demand: tests/dummy_data/Load_RealTime/##/2015.csv
Description: Dummy configuration file for testing purposes. Two fictitious zones (Z1
  and Z2) are simulated. The simulated period is only 7 days. There is a CHP unit
  in zone 1
FFRGainLimit: ''
FFRLimit: ''
FrequencyStability: ''
GAMS_folder: ''
GeoData: tests/dummy_data/Geo_Coordinates.csv
GridData: ''
H2FlexibleCapacity: tests/dummy_data/boundary_sector/BS_NTCs.csv
H2FlexibleDemand: tests/dummy_data/boundary_sector/BS_Inputs.csv
H2RigidDemand: tests/dummy_data/boundary_sector/BS_Demand.csv
HeatDemand: ''
HorizonLength: 4
HydroScheduling: Regional
HydroSchedulingHorizon: Annual
InertiaLimit: ''
InitialFinalReservoirLevel: 1
Interconnections: ''
LoadShedding: ''
LookAhead: 1
NTC: tests/dummy_data/NTCs.csv
Outages: ''
PowerPlantData: tests/dummy_data/boundary_sector/BS_Units_testcase.csv
PriceOfAmmonia: ''
PriceOfBiomass: Database/FuelPrices/Biomass/2015.csv
PriceOfBlackCoal: Database/FuelPrices/Coal/2015.csv
PriceOfCO2: ''
PriceOfFuelOil: Database/FuelPrices/Oil/2015.csv
PriceOfGas: Database/FuelPrices/Gas/2015.csv
PriceOfLignite: ''
PriceOfNuclear: ''
PriceOfPeat: tests/dummy_data/PriceOfPeat.csv
PriceTransmission: ''
PrimaryReserveLimit: ''
RenewablesAF: tests/dummy_data/AvailabilityFactors/##/2015.csv
Reserve2D: ''
Reserve2U: ''
ReserveCalculation: Probabilistic
ReserveParticipation:
- COMC
- GTUR
- HDAM
- HPHS
- ICEN
- CAES
- BATS
- BEVS
- P2HT
- ABHP
- ASHP
- GSHP
- HYHP
- WSHP
- REHE
ReserveParticipation_CHP:
- COMC
- GTUR
- ICEN
- STUR
ReservoirLevels: ''
ReservoirScaledInflows: ''
SectorCoupling: ''
SectorXAlertLevel: ''
SectorXDemand: tests/dummy_data/boundary_sector/BS_Spillage_Capacity.csv
SectorXFlexibleDemand: ''
SectorXFlexibleSupply: ''
SectorXFloodControl: ''
SectorXReservoirLevels: ''
ShareOfFlexibleDemand: ''
SimulationDirectory: Simulations/simulation_test_bs
SimulationTimeStep: 1.0
SimulationType: Standard
StartDate: !!python/tuple
- 2015
- 1
- 1
- 0
- 0
- 0
StopDate: !!python/tuple
- 2015
- 1
- 7
- 0
- 0
- 0
StorageAlertLevels: tests/dummy_data/boundary_sector/BS_CBFs.csv
StorageFloodControl: tests/dummy_data/boundary_sector/BS_FlexibleDemand.csv
SystemGainLimit: ''
Temperatures: tests/dummy_data/Temperatures.csv
TransmissionGridType: ''
WriteGDX: 1
WritePickle: 1
cplex_path: ''
default:
  CostCurtailment: 20.0
  CostH2Slack: 1000.0
  CostHeatSlack: 100.0
  CostLoadShedding: 400.0
  CostNotServed: ''
  CostOfSpillage: 1.0
  CostXNotServed: ''
  CostXSpillage: ''
  DemandFlexibility: 4.0
  FFRGainLimit: ''
  FFRLimit: ''
  InertiaLimit: ''
  LoadShedding: 0.05
  PriceOfAmmonia: 76.0
  PriceOfBiomass: 33.0
  PriceOfBlackCoal: 18.0
  PriceOfCO2: 90.0
  PriceOfFuelOil: 60.0
  PriceOfGas: 44.0
  PriceOfLignite: 15.0
  PriceOfNuclear: 4.0
  PriceOfPeat: 33.0
  PriceTransmission: 0.0
  PrimaryReserveLimit: ''
  ReservoirLevelFinal: 0.5
  ReservoirLevelInitial: 0.5
  ShareOfFlexibleDemand: 0.1
  ShareOfQuickStartUnits: 0.5
  SystemGainLimit: ''
  ValueOfLostLoad: 100000.0
  WaterValue: 1500.0
modifiers:
  Demand: 0.16
  Solar: 1.0
  Storage: 1.0
  Wind: 10.0
mts_zones:
- Z1
- Z2
- ZZ3
zones:
- Z1
- Z2
- ZZ3
