Description: Dummy configuration file for testing purposes. Three fictitious zones
  (Z1, Z2 and ZZ3) are simulated. The simulated period is only 7 days. There is a
  CHP unit in zone 1
SimulationType: Integer clustering
SimulationDirectory: Simulations/simulation_test
StartDate: !!python/tuple
- 2015
- 1
- 1
- 0
- 0
- 0
StopDate: !!python/tuple
- 2015
- 1
- 7
- 0
- 0
- 0
DataTimeStep: 1
SimulationTimeStep: 1
HorizonLength: 3
LookAhead: 1
AllowCurtailment: 1
GAMS_folder: ''
Demand: tests/dummy_data/Load_RealTime/##/2015.csv
RenewablesAF: tests/dummy_data/AvailabilityFactors/##/2015.csv
Outages: tests/dummy_data/Outages.csv
ShareOfFlexibleDemand: tests/dummy_data/ShareFlex.csv
DemandFlexibility: ''
LoadShedding: ''
PowerPlantData: tests/dummy_data/Units_testcase.csv
NTC: tests/dummy_data/NTCs.csv
Interconnections: tests/dummy_data/CrossBorderFlows.csv
TransmissionGridType: NTC
GridData: tests/dummy_data/GridData.csv
GeoData: tests/dummy_data/Geo_Coordinates.csv
HydroScheduling: Regional
HydroSchedulingHorizon: Annual
InitialFinalReservoirLevel: 1
ReservoirLevels: tests/dummy_data/ReservoirLevels.csv
ReservoirLevelInitial: ''
ReservoirLevelFinal: ''
ReservoirScaledInflows: tests/dummy_data/ScaledInflows.csv
StorageAlertLevels: ''
StorageFloodControl: ''
WaterValue: ''
CostLoadShedding: ''
CostCurtailment: 20
CostOfSpillage: tests/dummy_data/boundary_sector/BS_Spillage_cost.csv
ValueOfLostLoad: ''
PriceTransmission: ''
PriceOfGas: Database/FuelPrices/Gas/2015.csv
PriceOfBlackCoal: Database/FuelPrices/Coal/2015.csv
PriceOfLignite: ''
PriceOfCO2: ''
PriceOfBiomass: Database/FuelPrices/Biomass/2015.csv
PriceOfFuelOil: Database/FuelPrices/Oil/2015.csv
PriceOfNuclear: ''
PriceOfPeat: tests/dummy_data/PriceOfPeat.csv
PriceOfAmmonia: ''
ReserveCalculation: Generic
ShareOfQuickStartUnits: ''
Reserve2U: ''
Reserve2D: ''
PrimaryReserveLimit: ''
InertiaLimit: ''
FFRLimit: ''
FFRGainLimit: ''
FrequencyStability: ''
SystemGainLimit: ''
BoundarySectorData: tests/dummy_data/boundary_sector/BS_Inputs.csv
BoundarySectorNTC: tests/dummy_data/boundary_sector/BS_NTCs.csv
BoundarySectorInterconnections: tests/dummy_data/boundary_sector/BS_NTCs.csv
SectorXDemand: tests/dummy_data/boundary_sector/BS_Demand.csv
SectorXFlexibleDemand: tests/dummy_data/boundary_sector/BS_FlexibleDemand.csv
SectorXFlexibleSupply: tests/dummy_data/boundary_sector/BS_FlexibleSupply.csv
SectorXReservoirLevels: tests/dummy_data/boundary_sector/BS_ReservoirLevels.csv
SectorXFloodControl: tests/dummy_data/boundary_sector/BS_Flood_control.csv
BoundarySectorMaxSpillage: tests/dummy_data/boundary_sector/BS_Spillage_Capacity.csv
OptimalityGap: 0.0006
modifiers:
  Demand: 0.17
  Solar: 5
  Wind: 5
  Storage: 1
zones:
- Z1
- Z2
- ZZ3
mts_zones:
- Z1
- Z2
- ZZ3
all_zones:
- Z1
- Z2
- ZZ3
ReserveParticipation:
- COMC
- GTUR
- HDAM
- HPHS
- ICEN
- CAES
- BATS
- BEVS
- P2HT
- ABHP
- ASHP
- GSHP
- HYHP
- WSHP
- REHE
- GTUR
- ICEN
ReserveParticipation_CHP:
- GTUR
- ICEN
default:
  ShareOfFlexibleDemand: 0.03
  DemandFlexibility: 4
  LoadShedding: 0.05
  ReservoirLevelInitial: 0.5
  ReservoirLevelFinal: 0.5
  WaterValue: 400
  CostLoadShedding: 1500
  CostCurtailment: 20
  CostOfSpillage: 401
  ValueOfLostLoad: 100000
  PriceTransmission: 0
  PriceOfGas: 44
  PriceOfBlackCoal: 18
  PriceOfLignite: 15
  PriceOfCO2: 90
  PriceOfBiomass: 33
  PriceOfFuelOil: 60
  PriceOfNuclear: 4
  PriceOfPeat: 33
  PriceOfAmmonia: 76
  ShareOfQuickStartUnits: 0.5
  PrimaryReserveLimit: ''
  InertiaLimit: ''
  FFRLimit: ''
  FFRGainLimit: ''
  SystemGainLimit: ''
