Description: Standard simulation for 6 countries, with an integer clustering formulation
  (a typical unit is taken for each technology and multiplied N times)
SimulationType: Integer clustering
SimulationDirectory: Simulations/simulation_integer
StartDate: !!python/tuple
- 2015
- 1
- 1
- 0
- 0
- 0
StopDate: !!python/tuple
- 2015
- 1
- 6
- 0
- 0
- 0
DataTimeStep: 1
SimulationTimeStep: 1
HorizonLength: 3
LookAhead: 1
AllowCurtailment: 1
GAMS_folder: ''
Demand: Database/Load_RealTime/##/1h/2015.csv
RenewablesAF: Database/AvailabilityFactors/##/1h/2015.csv
Outages: ''
ShareOfFlexibleDemand: ''
DemandFlexibility: ''
LoadShedding: ''
PowerPlantData: Database/PowerPlants/##/2015.csv
NTC: ''
Interconnections: Database/CrossBorderFlows/1h/2015.csv
TransmissionGridType: NTC
GridData: ''
GeoData: ''
HydroScheduling: 'Off'
HydroSchedulingHorizon: Annual
InitialFinalReservoirLevel: ''
ReservoirLevels: ''
ReservoirLevelInitial: ''
ReservoirLevelFinal: ''
ReservoirScaledInflows: Database/HydroData/ScaledInflows/##/1h/2015.csv
StorageAlertLevels: ''
StorageFloodControl: ''
WaterValue: ''
CostLoadShedding: ''
CostCurtailment: ''
CostOfSpillage: ''
CostNotServed: ''
CostXNotServed: ''
ValueOfLostLoad: ''
PriceTransmission: ''
PriceOfGas: Database/FuelPrices/Gas/2015.csv
PriceOfBlackCoal: Database/FuelPrices/Coal/2015.csv
PriceOfLignite: ''
PriceOfCO2: Database/HydroData/ReservoirLevel/##/1h/2015.csv
PriceOfBiomass: ''
PriceOfFuelOil: Database/FuelPrices/Oil/2015.csv
PriceOfNuclear: ''
PriceOfPeat: ''
PriceOfAmmonia: ''
ReserveCalculation: Generic
ShareOfQuickStartUnits: ''
Reserve2U: ''
Reserve2D: ''
PrimaryReserveLimit: ''
InertiaLimit: ''
FFRLimit: ''
FFRGainLimit: ''
FrequencyStability: ''
SystemGainLimit: ''
BoundarySectorData: ''
BoundarySectorNTC: ''
BoundarySectorInterconnections: ''
SectorXDemand: ''
SectorXFlexibleDemand: ''
SectorXFlexibleSupply: ''
SectorXReservoirLevels: ''
SectorXFloodControl: ''
BoundarySectorMaxSpillage: ''
OptimalityGap: 0.0006
modifiers:
  Demand: 1
  Solar: 1
  Wind: 1
  Storage: 1
zones:
- AT
- BE
- DE
- FR
- NL
all_zones:
- AT
- BE
- DE
- FR
- NL
ReserveParticipation:
- COMC
- GTUR
- HDAM
- HPHS
- ICEN
- CAES
- BATS
- BEVS
ReserveParticipation_CHP: []
default:
  ShareOfFlexibleDemand: 0
  DemandFlexibility: 0
  LoadShedding: 0.05
  ReservoirLevelInitial: 0.5
  ReservoirLevelFinal: 0.5
  WaterValue: 100
  CostLoadShedding: 400
  CostCurtailment: 20
  CostOfSpillage: 401
  CostNotServed: ''
  CostXNotServed: 0
  ValueOfLostLoad: 100000
  PriceTransmission: 0
  PriceOfGas: 20
  PriceOfBlackCoal: 11
  PriceOfLignite: 8
  PriceOfCO2: 7
  PriceOfBiomass: 37
  PriceOfFuelOil: 35
  PriceOfNuclear: 3
  PriceOfPeat: 0
  PriceOfAmmonia: 40
  ShareOfQuickStartUnits: 0.5
  PrimaryReserveLimit: ''
  InertiaLimit: ''
  FFRLimit: ''
  FFRGainLimit: ''
  SystemGainLimit: ''
