Description: Dummy configuration file for testing purposes. Two fictitious zones (Z1
  and Z2) are simulated. The simulated period is only 7 days. There is a CHP unit
  in zone 1
SimulationType: Integer clustering
SimulationDirectory: Simulations/simulation_test
StartDate: !!python/tuple
- 2015
- 1
- 1
- 0
- 0
- 0
StopDate: !!python/tuple
- 2015
- 1
- 7
- 0
- 0
- 0
DataTimeStep: '1'
SimulationTimeStep: '1'
HorizonLength: '3'
LookAhead: '1'
AllowCurtailment: '1'
OptimalityGap: '0.0006'
Demand: tests/dummy_data/Load_RealTime/##/2015.csv
RenewablesAF: tests/dummy_data/AvailabilityFactors/##/2015.csv
Outages: tests/dummy_data/Outages.csv
ShareOfFlexibleDemand: tests/dummy_data/ShareFlex.csv
PowerPlantData: tests/dummy_data/Units_testcase.csv
HydroScheduling: Regional
HydroSchedulingHorizon: Annual
ReservoirLevels: tests/dummy_data/ReservoirLevels.csv
ReservoirScaledInflows: tests/dummy_data/ScaledInflows.csv
PriceOfGas: Database/FuelPrices/Gas/2015.csv
PriceOfBlackCoal: Database/FuelPrices/Coal/2015.csv
PriceOfBiomass: Database/FuelPrices/Biomass/2015.csv
PriceOfFuelOil: Database/FuelPrices/Oil/2015.csv
ReserveCalculation: Generic
zones:
- Z1
- Z2
- ZZ3
mts_zones:
- Z1
- Z2
- ZZ3
all_zones:
- Z1
- Z2
- ZZ3
ReserveParticipation:
- COMC
- GTUR
- HDAM
- HPHS
- ICEN
- CAES
- BATS
- BEVS
- P2HT
- ABHP
- ASHP
- GSHP
- HYHP
- WSHP
- REHE
default:
  ShareOfFlexibleDemand: 0.03
  DemandFlexibility: 4
  LoadShedding: 0.05
  CostLoadShedding: 1500
  CostCurtailment: 20
  PriceOfGas: 44
  PriceOfBlackCoal: 18
  PriceOfLignite: 15
  PriceOfCO2: 90
  PriceOfBiomass: 33
  PriceOfFuelOil: 60
