Description: 4 EU countries with exogenous flexible demands
SimulationType: Integer clustering
SimulationDirectory: Simulations/simulationEU
StartDate: !!python/tuple
- 2016
- 1
- 1
- 0
- 0
- 0
StopDate: !!python/tuple
- 2016
- 12
- 31
- 0
- 0
- 0
DataTimeStep: 1
SimulationTimeStep: 1
HorizonLength: 2
LookAhead: 1
AllowCurtailment: 1
GAMS_folder: ''
Demand: Database/TotalLoadValue/##/1h/2016.csv
RenewablesAF: Database/AvailabilityFactors/##/1h/2016.csv
Outages: Database/OutageFactors/##/2016.csv
ShareOfFlexibleDemand: Database/TotalLoadValue/ShareFlexibleDemandEU.csv
DemandFlexibility: ''
LoadShedding: ''
PowerPlantData: Database/PowerPlants/##/clustered.csv
NTC: ''
Interconnections: Database/CrossBorderFlows/1h/2016.csv
TransmissionGridType: NTC
GridData: ''
GeoData: ''
HydroScheduling: 'Off'
HydroSchedulingHorizon: Annual
InitialFinalReservoirLevel: 1
ReservoirLevels: Database/HydroData/ScaledLevels/##/1h/2016.csv
ReservoirLevelInitial: ''
ReservoirLevelFinal: ''
ReservoirScaledInflows: Database/HydroData/ScaledInflows/##/1h/2016_profile_from_2012.csv
StorageAlertLevels: ''
StorageFloodControl: ''
WaterValue: ''
CostLoadShedding: ''
CostCurtailment: ''
CostOfSpillage: ''
CostNotServed: ''
CostXNotServed: ''
ValueOfLostLoad: ''
PriceTransmission: ''
PriceOfGas: ''
PriceOfBlackCoal: ''
PriceOfLignite: ''
PriceOfCO2: ''
PriceOfBiomass: ''
PriceOfFuelOil: ''
PriceOfNuclear: ''
PriceOfPeat: ''
PriceOfAmmonia: ''
ReserveCalculation: Generic
ShareOfQuickStartUnits: ''
Reserve2U: ''
Reserve2D: ''
PrimaryReserveLimit: ''
InertiaLimit: ''
FFRLimit: ''
FFRGainLimit: ''
FrequencyStability: ''
SystemGainLimit: ''
BoundarySectorData: ''
BoundarySectorNTC: ''
BoundarySectorInterconnections: ''
SectorXDemand: ''
SectorXFlexibleDemand: ''
SectorXFlexibleSupply: ''
SectorXReservoirLevels: ''
SectorXFloodControl: ''
BoundarySectorMaxSpillage: ''
OptimalityGap: 0.0006
modifiers:
  Demand: 1
  Solar: 1
  Wind: 1
  Storage: 1
zones:
- BE
- DE
- FR
- NL
all_zones:
- BE
- DE
- FR
- NL
ReserveParticipation:
- COMC
- GTUR
- HDAM
- HPHS
- ICEN
- CAES
- BATS
- BEVS
ReserveParticipation_CHP: []
default:
  ShareOfFlexibleDemand: 0.03
  DemandFlexibility: 4
  LoadShedding: 0.05
  ReservoirLevelInitial: 0.5
  ReservoirLevelFinal: 0.5
  WaterValue: 400
  CostLoadShedding: 400
  CostCurtailment: 20
  CostOfSpillage: 1
  CostNotServed: ''
  CostXNotServed: 0
  ValueOfLostLoad: 100000
  PriceTransmission: 0
  PriceOfGas: 20
  PriceOfBlackCoal: 11
  PriceOfLignite: 8
  PriceOfCO2: 7
  PriceOfBiomass: 13
  PriceOfFuelOil: 35
  PriceOfNuclear: 3
  PriceOfPeat: 8
  PriceOfAmmonia: 76
  ShareOfQuickStartUnits: 0.5
  PrimaryReserveLimit: ''
  InertiaLimit: ''
  FFRLimit: ''
  FFRGainLimit: ''
  SystemGainLimit: ''
